[2025-09-30T00:00:02.122+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-30T00:00:02.127+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_data scheduled__2025-09-29T00:00:00+00:00 [queued]>
[2025-09-30T00:00:02.130+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_data scheduled__2025-09-29T00:00:00+00:00 [queued]>
[2025-09-30T00:00:02.130+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-30T00:00:02.135+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_data> on 2025-09-29 00:00:00+00:00
[2025-09-30T00:00:02.138+0000] {standard_task_runner.py:64} INFO - Started process 23956 to run task
[2025-09-30T00:00:02.140+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_data', 'scheduled__2025-09-29T00:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmp7j4tda5e']
[2025-09-30T00:00:02.141+0000] {standard_task_runner.py:91} INFO - Job 249: Subtask collect_data
[2025-09-30T00:00:02.158+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_data scheduled__2025-09-29T00:00:00+00:00 [running]> on host 2b301b74205f
[2025-09-30T00:00:02.189+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-29T00:00:00+00:00'
[2025-09-30T00:00:02.189+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-30T00:00:02.198+0000] {kudryakov_hw1-checkpoint.py:78} INFO - Началась загрузка данных
[2025-09-30T00:00:02.222+0000] {kudryakov_hw1-checkpoint.py:85} INFO - Данные получили
[2025-09-30T00:00:02.229+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-30T00:00:02.229+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-30T00:00:03.535+0000] {kudryakov_hw1-checkpoint.py:94} INFO - Данные успешно загружены
[2025-09-30T00:00:03.537+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-30T00:00:03.538+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-30T00:00:03.546+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hw1, task_id=collect_data, run_id=scheduled__2025-09-29T00:00:00+00:00, execution_date=20250929T000000, start_date=20250930T000002, end_date=20250930T000003
[2025-09-30T00:00:03.574+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-30T00:00:03.589+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-30T00:00:03.590+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
