[2025-10-01T00:00:02.013+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-01T00:00:02.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_data scheduled__2025-09-30T00:00:00+00:00 [queued]>
[2025-10-01T00:00:02.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_data scheduled__2025-09-30T00:00:00+00:00 [queued]>
[2025-10-01T00:00:02.023+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-01T00:00:02.027+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_data> on 2025-09-30 00:00:00+00:00
[2025-10-01T00:00:02.031+0000] {standard_task_runner.py:64} INFO - Started process 30022 to run task
[2025-10-01T00:00:02.033+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_data', 'scheduled__2025-09-30T00:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmp1t207cgz']
[2025-10-01T00:00:02.034+0000] {standard_task_runner.py:91} INFO - Job 255: Subtask collect_data
[2025-10-01T00:00:02.052+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_data scheduled__2025-09-30T00:00:00+00:00 [running]> on host 2b301b74205f
[2025-10-01T00:00:02.084+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-30T00:00:00+00:00'
[2025-10-01T00:00:02.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-01T00:00:02.092+0000] {kudryakov_hw1-checkpoint.py:78} INFO - Началась загрузка данных
[2025-10-01T00:00:02.116+0000] {kudryakov_hw1-checkpoint.py:85} INFO - Данные получили
[2025-10-01T00:00:02.124+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-10-01T00:00:02.124+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-10-01T00:00:03.467+0000] {kudryakov_hw1-checkpoint.py:94} INFO - Данные успешно загружены
[2025-10-01T00:00:03.470+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-01T00:00:03.471+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-01T00:00:03.479+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hw1, task_id=collect_data, run_id=scheduled__2025-09-30T00:00:00+00:00, execution_date=20250930T000000, start_date=20251001T000002, end_date=20251001T000003
[2025-10-01T00:00:03.507+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-01T00:00:03.522+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-01T00:00:03.523+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
