[2025-09-25T20:52:03.752+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T20:52:03.758+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_metrics_pipeline manual__2025-09-25T20:46:41.026639+00:00 [queued]>
[2025-09-25T20:52:03.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_metrics_pipeline manual__2025-09-25T20:46:41.026639+00:00 [queued]>
[2025-09-25T20:52:03.762+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-25T20:52:03.770+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_metrics_pipeline> on 2025-09-25 20:46:41.026639+00:00
[2025-09-25T20:52:03.774+0000] {standard_task_runner.py:64} INFO - Started process 76275 to run task
[2025-09-25T20:52:03.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_metrics_pipeline', 'manual__2025-09-25T20:46:41.026639+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmpf8i_zu3y']
[2025-09-25T20:52:03.778+0000] {standard_task_runner.py:91} INFO - Job 212: Subtask collect_metrics_pipeline
[2025-09-25T20:52:03.801+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_metrics_pipeline manual__2025-09-25T20:46:41.026639+00:00 [running]> on host 2b301b74205f
[2025-09-25T20:52:03.839+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_metrics_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T20:46:41.026639+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T20:46:41.026639+00:00'
[2025-09-25T20:52:03.840+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T20:52:03.854+0000] {kudryakov_hw1-checkpoint.py:240} INFO - Начинаем сбор метрик пайплайна
[2025-09-25T20:52:03.875+0000] {logging_mixin.py:188} INFO - {'pipeline_start': datetime.datetime(2025, 9, 25, 20, 46, 42, 131560), 'pipeline_end': datetime.datetime(2025, 9, 25, 20, 47, 1, 61904), 'total_duration': 18.930344, 'split_and_preprocess_start': datetime.datetime(2025, 9, 25, 20, 46, 45, 118807), 'split_and_preprocess_end': datetime.datetime(2025, 9, 25, 20, 46, 49, 977925), 'train_start': datetime.datetime(2025, 9, 25, 20, 46, 51, 446227), 'train_end': datetime.datetime(2025, 9, 25, 20, 46, 56, 325134), 'train_duration_seconds': 4.88, 'collect_metrics_start': datetime.datetime(2025, 9, 25, 20, 46, 57, 428682), 'collect_metrics_end': datetime.datetime(2025, 9, 25, 20, 47, 1, 61904), 'author': 'VLADISLAV KUDRYAKOV'} pipeline_metrics
[2025-09-25T20:52:03.875+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T20:52:03.876+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 268, in collect_metrics_pipeline
    s3_write_json(s3_hook, pipeline_metrics, S3_BUCKET, S3_KEY_PIPELINE_METRICS)
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 54, in s3_write_json
    json_str = json.dumps(data, indent=2, ensure_ascii=False)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[2025-09-25T20:52:03.879+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hw1, task_id=collect_metrics_pipeline, run_id=manual__2025-09-25T20:46:41.026639+00:00, execution_date=20250925T204641, start_date=20250925T205203, end_date=20250925T205203
[2025-09-25T20:52:03.884+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 212 for task collect_metrics_pipeline (Object of type datetime is not JSON serializable; 76275)
[2025-09-25T20:52:03.917+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T20:52:03.924+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T20:52:03.924+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
