[2025-09-25T20:21:30.786+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T20:21:30.792+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_metrics_model manual__2025-09-25T20:21:14.086804+00:00 [queued]>
[2025-09-25T20:21:30.796+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_metrics_model manual__2025-09-25T20:21:14.086804+00:00 [queued]>
[2025-09-25T20:21:30.796+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-25T20:21:30.800+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_metrics_model> on 2025-09-25 20:21:14.086804+00:00
[2025-09-25T20:21:30.803+0000] {standard_task_runner.py:64} INFO - Started process 71122 to run task
[2025-09-25T20:21:30.806+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_metrics_model', 'manual__2025-09-25T20:21:14.086804+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/kudryakov_hw1.py', '--cfg-path', '/tmp/tmpqu31jysc']
[2025-09-25T20:21:30.807+0000] {standard_task_runner.py:91} INFO - Job 169: Subtask collect_metrics_model
[2025-09-25T20:21:30.824+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_metrics_model manual__2025-09-25T20:21:14.086804+00:00 [running]> on host 2b301b74205f
[2025-09-25T20:21:30.854+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_metrics_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T20:21:14.086804+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T20:21:14.086804+00:00'
[2025-09-25T20:21:30.855+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T20:21:30.859+0000] {logging_mixin.py:188} INFO - collect_metrics_model
[2025-09-25T20:21:30.859+0000] {kudryakov_hw1.py:203} INFO - Начали расчет метрик
[2025-09-25T20:21:30.867+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-25T20:21:30.867+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-25T20:21:34.585+0000] {logging_mixin.py:188} INFO - {'r_squared': 0.8503834409713716, 'RMSE': 0.19244684232083303} metrics
[2025-09-25T20:21:34.588+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T20:21:34.589+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kudryakov_hw1.py", line 220, in collect_metrics_model
    s3_write_json(s3_hook, metrics, S3_BUCKET, S3_KEY_MODEL_METRICS)
  File "/opt/airflow/dags/kudryakov_hw1.py", line 57, in s3_write_json
    hook.load_file_obj(file_obj=json_str, key=key, bucket_name=bucket, replace=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 158, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 132, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1234, in load_file_obj
    self._upload_file_obj(file_obj, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1255, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 624, in upload_fileobj
    raise ValueError('Fileobj must implement read')
ValueError: Fileobj must implement read
[2025-09-25T20:21:34.604+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=hw1, task_id=collect_metrics_model, run_id=manual__2025-09-25T20:21:14.086804+00:00, execution_date=20250925T202114, start_date=20250925T202130, end_date=20250925T202134
[2025-09-25T20:21:34.615+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 169 for task collect_metrics_model (Fileobj must implement read; 71122)
[2025-09-25T20:21:34.654+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T20:21:34.672+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T20:21:34.673+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
