[2025-09-25T18:51:16.139+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T18:51:16.151+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.train_model manual__2025-09-25T18:45:57.350350+00:00 [queued]>
[2025-09-25T18:51:16.156+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.train_model manual__2025-09-25T18:45:57.350350+00:00 [queued]>
[2025-09-25T18:51:16.156+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-25T18:51:16.164+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2025-09-25 18:45:57.350350+00:00
[2025-09-25T18:51:16.170+0000] {standard_task_runner.py:64} INFO - Started process 57896 to run task
[2025-09-25T18:51:16.172+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'train_model', 'manual__2025-09-25T18:45:57.350350+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmpc_8_mmh3']
[2025-09-25T18:51:16.174+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask train_model
[2025-09-25T18:51:16.203+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.train_model manual__2025-09-25T18:45:57.350350+00:00 [running]> on host 2b301b74205f
[2025-09-25T18:51:16.247+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T18:45:57.350350+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T18:45:57.350350+00:00'
[2025-09-25T18:51:16.248+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T18:51:16.255+0000] {kudryakov_hw1-checkpoint.py:159} INFO - Начали обучение модели start-ts 2025-09-25T18:51:16.255120
[2025-09-25T18:51:16.260+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-25T18:51:16.261+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-25T18:51:21.370+0000] {kudryakov_hw1-checkpoint.py:174} INFO - Закончили обучение модели end-ts 2025-09-25T18:51:21.370790
[2025-09-25T18:51:21.907+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T18:51:21.909+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 186, in train_model
    s3_write_csv(s3_hook, S3_BUCKET, y_pred, "2025/processed_data/titanic/titanic_y_pred.csv")
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 47, in s3_write_csv
    df.to_csv(buf, index=False)
AttributeError: 'str' object has no attribute 'to_csv'
[2025-09-25T18:51:21.926+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hw1, task_id=train_model, run_id=manual__2025-09-25T18:45:57.350350+00:00, execution_date=20250925T184557, start_date=20250925T185116, end_date=20250925T185121
[2025-09-25T18:51:21.941+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task train_model ('str' object has no attribute 'to_csv'; 57896)
[2025-09-25T18:51:21.968+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T18:51:21.986+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T18:51:21.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
