[2025-09-25T16:15:37.629+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T16:15:37.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_data manual__2025-09-25T16:15:35.077198+00:00 [queued]>
[2025-09-25T16:15:37.637+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_data manual__2025-09-25T16:15:35.077198+00:00 [queued]>
[2025-09-25T16:15:37.637+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-25T16:15:37.641+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_data> on 2025-09-25 16:15:35.077198+00:00
[2025-09-25T16:15:37.644+0000] {standard_task_runner.py:64} INFO - Started process 37263 to run task
[2025-09-25T16:15:37.646+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_data', 'manual__2025-09-25T16:15:35.077198+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmp4rhrmn8f']
[2025-09-25T16:15:37.647+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask collect_data
[2025-09-25T16:15:37.663+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_data manual__2025-09-25T16:15:35.077198+00:00 [running]> on host 2b301b74205f
[2025-09-25T16:15:37.692+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T16:15:35.077198+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T16:15:35.077198+00:00'
[2025-09-25T16:15:37.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T16:15:37.697+0000] {kudryakov_hw1-checkpoint.py:68} INFO - Началась загрузка данных
[2025-09-25T16:15:37.697+0000] {kudryakov_hw1-checkpoint.py:69} INFO - Началась загрузка данных
[2025-09-25T16:15:37.719+0000] {kudryakov_hw1-checkpoint.py:76} INFO - Данные получили
[2025-09-25T16:15:37.720+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T16:15:37.720+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 81, in collect_data
    X_final.to_pickle(filebuffer)
NameError: name 'X_final' is not defined
[2025-09-25T16:15:37.723+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=hw1, task_id=collect_data, run_id=manual__2025-09-25T16:15:35.077198+00:00, execution_date=20250925T161535, start_date=20250925T161537, end_date=20250925T161537
[2025-09-25T16:15:37.727+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task collect_data (name 'X_final' is not defined; 37263)
[2025-09-25T16:15:37.744+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T16:15:37.750+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T16:15:37.751+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
