[2025-09-25T16:08:17.403+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T16:08:17.409+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_data manual__2025-09-25T16:03:10.148012+00:00 [queued]>
[2025-09-25T16:08:17.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_data manual__2025-09-25T16:03:10.148012+00:00 [queued]>
[2025-09-25T16:08:17.412+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-25T16:08:17.417+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_data> on 2025-09-25 16:03:10.148012+00:00
[2025-09-25T16:08:17.422+0000] {standard_task_runner.py:64} INFO - Started process 36087 to run task
[2025-09-25T16:08:17.424+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_data', 'manual__2025-09-25T16:03:10.148012+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmp_w0g25kb']
[2025-09-25T16:08:17.425+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask collect_data
[2025-09-25T16:08:17.454+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_data manual__2025-09-25T16:03:10.148012+00:00 [running]> on host 2b301b74205f
[2025-09-25T16:08:17.486+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T16:03:10.148012+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T16:03:10.148012+00:00'
[2025-09-25T16:08:17.486+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T16:08:17.493+0000] {kudryakov_hw1-checkpoint.py:63} INFO - Началась загрузка данных
[2025-09-25T16:08:17.520+0000] {kudryakov_hw1-checkpoint.py:70} INFO - Данные получили
[2025-09-25T16:08:17.520+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T16:08:17.520+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 75, in collect_data
    X_final.to_pickle(filebuffer)
NameError: name 'X_final' is not defined
[2025-09-25T16:08:17.524+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hw1, task_id=collect_data, run_id=manual__2025-09-25T16:03:10.148012+00:00, execution_date=20250925T160310, start_date=20250925T160817, end_date=20250925T160817
[2025-09-25T16:08:17.529+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task collect_data (name 'X_final' is not defined; 36087)
[2025-09-25T16:08:17.571+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T16:08:17.578+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T16:08:17.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
