[2025-09-25T19:00:50.581+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T19:00:50.588+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_metrics_model manual__2025-09-25T19:00:31.636468+00:00 [queued]>
[2025-09-25T19:00:50.592+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_metrics_model manual__2025-09-25T19:00:31.636468+00:00 [queued]>
[2025-09-25T19:00:50.592+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-25T19:00:50.598+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_metrics_model> on 2025-09-25 19:00:31.636468+00:00
[2025-09-25T19:00:50.602+0000] {standard_task_runner.py:64} INFO - Started process 59548 to run task
[2025-09-25T19:00:50.604+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_metrics_model', 'manual__2025-09-25T19:00:31.636468+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmp_r4c9wk2']
[2025-09-25T19:00:50.605+0000] {standard_task_runner.py:91} INFO - Job 109: Subtask collect_metrics_model
[2025-09-25T19:00:50.626+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_metrics_model manual__2025-09-25T19:00:31.636468+00:00 [running]> on host 2b301b74205f
[2025-09-25T19:00:50.665+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_metrics_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T19:00:31.636468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T19:00:31.636468+00:00'
[2025-09-25T19:00:50.666+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T19:00:50.672+0000] {logging_mixin.py:188} INFO - collect_metrics_model
[2025-09-25T19:00:50.672+0000] {kudryakov_hw1-checkpoint.py:198} INFO - Начали расчет метрик
[2025-09-25T19:00:50.676+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-25T19:00:50.677+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-25T19:00:54.200+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T19:00:54.202+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 212, in collect_metrics_model
    s3_write_json(s3_hook, y_test, S3_BUCKET, "2025/metrics/titanic/" + S3_KEY_MODEL_METRICS)
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 54, in s3_write_json
    json_str = json.dumps(data, indent=2, ensure_ascii=False)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2025-09-25T19:00:54.217+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=hw1, task_id=collect_metrics_model, run_id=manual__2025-09-25T19:00:31.636468+00:00, execution_date=20250925T190031, start_date=20250925T190050, end_date=20250925T190054
[2025-09-25T19:00:54.227+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 109 for task collect_metrics_model (Object of type DataFrame is not JSON serializable; 59548)
[2025-09-25T19:00:54.284+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T19:00:54.301+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T19:00:54.302+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
